#!/usr/bin/perl

# Used to install LogZilla on a new Ubuntu 12 and 13 LTS x64 server

use strict;
use warnings;
use Getopt::Long;

my $osver = `lsb_release -d -s | awk '{print \$2}' | cut -d '.' -f1-2`;
chomp($osver);
if ( $osver !~ /12|14/ ) {
    print("\033[1mThis tool will only run on Ubuntu 12.x or 14.x!\n\033[0m");
    exit;
}

my $login = ( getpwuid $> );
print "You must run this script as root.\nTry \"sudo su -\" to login as root\n" if $login ne 'root';

# Command line options
my $options = {
    debug       => 0,
    verbose     => 0,
    lzroot      => "/var/www/logzilla",
    help        => 0,
    spx_compile => 1,
    checkout    => 1,
    install     => 1,
    prereqs     => 1,
    apache      => 1,
    ng          => 1,
    license     => 1,
    agree       => 0,
    vmbanner    => 0,
    alias       => 1,
    mypass      => "mysql",
};

sub usage_and_exit {
    my ($exit_code) = @_;
    my $myname = $0;
    $myname =~ s{.*/}{};    # leave just program name without path
    print STDERR qq{
    This program is used to install LogZilla v4.x onto a fresh OS installation of Ubuntu 12 or 13 LTS x64 only.
    Using it for anything else may break the install.
    Usage: $myname [-hdvl] 
    -h        : this (help) message
    -d        : debug level (0-5) (0 = disabled [default])
    -v        : Also print results to STDERR
    -mypass   : Set the password for the root mysql user (default: mysql)
    -b        : set the base directory for logzilla (defaults to $options->{lzroot})
    -vmb      : Create console boot banner (for VMWare deployments) (default 0)
    -alias    : Create bash_aliases for both root and lzadmin user (if exists) (default 1)
    -s        : Compile Sphinx (default 1)
    -c        : Checkout SVN (default 1)
    -i        : Install LogZilla (default 1)
    -p        : Install System Prerequisites (default 1)
    -a        : Set up Apache (default 1)
    -ng       : Set up syslog-ng (default 1)
    -agree    : Agree to the license terms and to this install method (default 0)
    Example: ./$myname -d 1 -v -base "/var/www/logzilla" -s 0 -c 0 -i 0 -p 0 -a 0 -ng 0 -alias 0 -agree 1 -mypass mysqlrootpass
    };
    exit($exit_code);
}

GetOptions(
    'debug|d=i'       => \$options->{debug},
    'help|h!'         => \$options->{help},
    'verbose|v!'      => \$options->{verbose},
    'base|b=s'        => \$options->{lzroot},
    'spx_compile|s=i' => \$options->{spx_compile},
    'checkout|c=i'    => \$options->{checkout},
    'install|i=i'     => \$options->{install},
    'prereqs|p=i'     => \$options->{prereqs},
    'apache|a=i'      => \$options->{apache},
    'ng|ng=i'         => \$options->{ng},
    'license|lic=i'   => \$options->{license},
    'agree=i'         => \$options->{agree},
    'vmbanner|vmb=i'  => \$options->{vmbanner},
    'alias=i'         => \$options->{alias},
    'mypass=s'        => \$options->{mypass},
) or usage_and_exit(1);    # got some invalid options

if ( $options->{help} ) {
    usage_and_exit(0);
}
if ( $options->{agree} eq 0 ) {
    print "\n\n################################################################################\n";
    print("\033[1mWARNING!\n\033[0m");
    print("\033[1mThis script was contributed to auto-install on Ubuntu 12 or 13 LTS Server x_64!\n\033[0m");
    print("\033[1mYou must agree to the LogZilla license terms by using -agree 1\n\033[0m");
    print("\033[1mBe sure you understand the implications of using this script before running it.\n\033[0m");
    print "################################################################################\n";
    usage_and_exit(0);
}

my $cmd;

# Install Prereq's
if ( $options->{prereqs} > 0 ) {
my $sngpath = $osver;
$sngpath = "trusty" if $osver eq 14.04;
    print "Making sure OS is up to date...\n";
    system("printf '# Replacement for the default syslog-ng included in Ubuntu as that one has a memory leak\ndeb http://packages.madhouse-project.org/ubuntu $sngpath syslog-ng-3.6\n' > /etc/apt/sources.list.d/syslog-ng_logzilla.list");
    system("wget --no-check-certificate https://packages.madhouse-project.org/debian/archive-key.txt");
    system("apt-key add archive-key.txt");
    system("apt-get update && apt-get -y upgrade");
    system("apt-get -y purge rsyslog && apt-get -y install syslog-ng");
    print "Installing system prerequisites 1 of 9\n";
    system("apt-get -y --force-yes install build-essential apache2 mysql-server php5 libmysqlclient-dev php5-cli libapache2-mod-php5 subversion");
    print "Installing system prerequisites 2 of 9\n";
    system("apt-get -y install linux-headers-\$(uname -r)");
    print "Installing system prerequisites 3 of 9\n";
    system("apt-get -y install php5-mysql php5-gd php5-json php5-xsl php5-gd php-pear php5-ldap");
    print "Installing system prerequisites 4 of 9\n";
    system("apt-get -y install libdate-calc-perl libfile-tail-perl libdbd-mysql-perl libmime-lite-perl libdata-random-perl libdate-simple-perl");
    print "Installing system prerequisites 5 of 9\n";
    system("apt-get -y install libstring-crc32-perl libmoose-perl libnet-snmp-perl libwww-perl libdigest-md5-file-perl");
    print "Installing system prerequisites 6 of 9\n";
    system("apt-get -y install libchi-perl 2>&1");
    print "Installing system prerequisites 7 of 9\n";
    system("apt-get -y install libfind-lib-perl 2>&1");
    print "Installing system prerequisites 8 of 8\n";
    system("apt-get -y install libmoosex-params-validate-perl librrdtool-oo-perl 2>&1");
    print "Installing system prerequisites 9 of 9\n";
    system("apt-get -y install libtest-deep-perl libtest-mocktime-perl libberkeleydb-perl libfile-slurp-perl libdigest-crc-perl libdevel-nytprof-perl curl cpanminus 2>&1");
}

$options->{mypass} = quotemeta($options->{mypass});
my $exit_code=system("mysql -uroot -p$options->{mypass} -e ''");
if($exit_code!=0) {
    print("\n\033[1m\tERROR!\n\033[0m");
    print "Unable to connect to the mysql server using the default password. Please use the -mypass option on the command line!\n";
    exit;
}

# Download code from subversion
if ( $options->{checkout} > 0 ) {
    my ( $svnroot, $install_dir ) = $options->{lzroot} =~ /(.*)\/(.*)$/;
    print "Downloading LogZilla\n";
    system("cd $svnroot && svn co https://subversion.assembla.com/svn/logzilla/ $install_dir 2>&1");
}

# Create the .lzrc file
my $rcfn = $options->{lzroot} . "/scripts/.lzrc";
print "Creating .lzrc at $rcfn\n";
open FILE, ">$rcfn" or die $!;
print FILE <<EOF;
#------------------# 
# basic properties # 
#------------------# 
\$dbroot = "root"; 
\$dbrootpass = "$options->{mypass}"; 
\$dbname = "syslog"; 
\$dbhost = "localhost"; 
\$dbport = "3306"; 
\$dbadmin = "syslogadmin"; # DO NOT USE ROOT HERE OR YOU WILL LOSE DB PERMISSIONS ON OTHER DB'S!
\$dbadminpw = "syslogadmin"; 
\$siteadmin = "admin"; 
\$siteadminpw = "admin"; 
\$email = "root\\\@localhost"; 
\$sitename = "LogZilla Server"; 
\$url = "/"; 
\$logpath = "/var/log/logzilla"; 
\$retention = "7"; 
\$snare = "Y";
\$syslogng_conf = "/etc/syslog-ng/conf.d/logzilla.conf";
\$syslogng_source = "s_logzilla";
\$webuser = "www-data";
\$skipdb = "N";
\$skipcron = "N";
\$skipsysng = "N";
\$skiplogrot = "N";
\$skipsudo = "N";
\$skipapparmor = "N";
\$skipfb = "N";
\$sphinx_compile = "N";
\$sphinx_index = "Y";
\$skip_ioncube = "N";
\$skiplic = "Y";
\$autoyes = "Y";
EOF
close FILE;
print "Editing .lzrc\n";
if ( $options->{spx_compile} > 0 ) {
    system("perl -i -pe 's|\\\$sphinx_compile = \"N\"|\\\$sphinx_compile = \"Y\"|g' $options->{lzroot}/scripts/.lzrc 2>&1");
} else {
    system("perl -i -pe 's|\\\$sphinx_compile = \"Y\"|\\\$sphinx_compile = \"N\"|g' $options->{lzroot}/scripts/.lzrc 2>&1");
}

# Customization for this script and a fresh syslog-ng install
# cdukes, 2015-04-21: Deprecated in favor of doing it during install
#if ( $options->{ng} > 0 ) {
    #add_syslog_conf();
#}

# Install LogZilla
if ( $options->{install} > 0 ) {
    print "Installing Perl Prerequisites\n";
    system("cpanm -n Spreadsheet::WriteExcel Test::mysqld PerlIO::Util Log::Fast Date::Calc LWP::Simple String::CRC32 MIME::Lite Net::SNMP CHI Excel::Writer::XLSX");
    print "Installing LogZilla\n";
    system("(cd $options->{lzroot}/scripts && echo \"q\"| sudo ./install) 2>&1");
}

# Set up Apache
if ( $options->{apache} > 0 ) {
    print "Setting up Apache\n";
    # cdukes: Ubuntu 13 changed the default config. We'll copy our config instead
    #my $file = "/etc/apache2/apache2.conf";
    #if ( -e "$file" ) {
    #open my $config, '+<', "$file" or warn "FAILED: $!\n";
    #my @arr = <$config>;
    #if ( !grep( /logzilla/, @arr ) ) {
    #system("perl -i -pe 's|#ServerRoot \"/etc/apache2\"|#ServerRoot \"/etc/apache2\"\nServerName \"logzilla\"|g' /etc/apache2/apache2.conf 2>&1");
    #}
    my $file = $options->{lzroot} . "/scripts/contrib/system_configs/logzilla.apache";
    if ( -e "$file" ) {
        unless ( -e "/etc/apache2/sites-available/logzilla.conf" ) {
            print "Copying $file to /etc/apache2/sites-available/logzilla.conf\n";
            system("cp $file /etc/apache2/sites-available/logzilla.conf 2>&1");
        }
        print "Disabling default site and enabling LogZilla site as the new default\n";
        if ( -e "/etc/apache2/sites-available/default") {
            system("a2dissite default 2>&1");
        }
        if ( -e "/etc/apache2/sites-available/000-default.conf") {
            system("a2dissite 000-default.conf 2>&1");
        }
        system("a2ensite logzilla.conf 2>&1");
        system("service apache2 restart 2>&1");
    } else {
        print "Unable to locate $file\n";
        exit;
    }
}

# Chown to the web user
print "Changing $options->{lzroot}/html to Apache user\n";
system("cd $options->{lzroot} && chown -R www-data:www-data html/ 2>&1");

# Modify the .lzrc so that sphinx_compile is disabled on subsequent upgrades
print "Disabling Sphinx compile for future upgrades\n";
system("perl -i -pe 's|\\\$sphinx_compile = \"Y\"|\\\$sphinx_compile = \"N\"|g' $options->{lzroot}/scripts/.lzrc 2>&1");
system("perl -i -pe 's|\\\$skiplic = \"Y\"|\\\$skiplic = \"N\"|g' $options->{lzroot}/scripts/.lzrc 2>&1");

if ( $options->{vmbanner} > 0 ) {
    print "Adding VM Startup options to system startup (/etc/rc.local)\n";
    my $file = "/etc/rc.local";
    if ( -e "$file" ) {
        open my $config, '+<', "$file" or warn "FAILED: $!\n";
        my @all = <$config>;
        if ( !grep( /vmstartup/, @all ) ) {
            seek $config, 0, 0;
            splice @all, -1, 0, "# <lzconfig>\n$options->{lzroot}/scripts/VM/vmstartup\n# </lzconfig>\n";
            print $config @all;
        }
        close $config;
    }
}

# Create bash aliases file
if ( $options->{alias} > 0 ) {

    # always do root
    &aliases('/root/.bash_aliases');

    # only do lzadmin if this is a default vmbuild and that user exists
    if ( getpwnam('lzadmin') ) {
        print "Creating .bash_aliases file for the 'lzadmin' user\n";
        &aliases('/home/lzadmin/.bash_aliases');
        system("chown lzadmin:lzadmin /home/lzadmin/.bash_aliases");
    }
}

sub aliases {
    my $file = shift;
    my @arr;
    system("touch $file");
    if ( -e "$file" ) {
        open my $aliases, '+<', "$file" or warn "FAILED: $!\n";
        @arr = <$aliases>;
        if ( !grep( /logzilla/, @arr ) ) {
            print "Creating bash aliases at $file\n";
            open FILE, ">>$file" or die $!;
            print FILE <<EOF;
export LZ='$options->{lzroot}'
export MY_ADMIN='root'
export MY_ADMIN_PWD='mysql'
# OS Related
alias df='df -h'
alias diff='diff -Nur'
alias dir='ls --color=auto --format=vertical'
alias du='du -h'
alias ll='ls --color -lh'
alias ls='ls --color=auto'
alias pa='ps -efwwwww | grep -v grep | grep \$1'
alias vi='vim'

# MySQL Related
alias mysql='mysql -u\$MY_ADMIN -p\$MY_ADMIN_PWD'
alias mysqladmin='mysqladmin -u\$MY_ADMIN -p\$MY_ADMIN_PWD'
alias mysqlcheck='mysqlcheck -u\$MY_ADMIN -p\$MY_ADMIN_PWD --auto-repair'
alias mysqldump='mysqldump -u\$MY_ADMIN -p\$MY_ADMIN_PWD'
alias mysqlreport='mysqlreport --user=\$MY_ADMIN --password=\$MY_ADMIN_PWD'
alias mysqlshow='mysqldump -u\$MY_ADMIN -p\$MY_ADMIN_PWD'
alias mytop='mytop -u\$MY_ADMIN -p\$MY_ADMIN_PWD'

# LogZilla related
alias mysqltuner='\$LZ/scripts/tools/mysqltuner.pl --user \$MY_ADMIN --pass \$MY_ADMIN_PWD'
alias summary='\$LZ/scripts/tools/summary'
alias lzupdate='(cd \$LZ && sudo svn update --accept theirs-conflict && echo "To upgrade, type: cd /var/www/logzilla/scripts && sudo ./upgrade")'

# Sphinx shortcuts
alias myspx='mysql -h0 -P9306'
alias spx_full='(cd \$LZ/sphinx && ./indexer.sh full)'
alias spx_delta='(cd \$LZ/sphinx && ./indexer.sh delta)'
alias spx_stop='(cd \$LZ/sphinx && ./run_searchd.sh --stop)'
alias spx_start='(cd \$LZ/sphinx && ./run_searchd.sh)'
EOF
        }
    }
}
my $checkprocess = `ps -C mysqld -o pid=`;
if ($checkprocess) {
    print "Stopping MySQL\n";
    system("service mysql stop");
}
&chk_ib_logs;
# Use the contrib script instead of here so we don't maintain two separate copies
# &setup_mycnf("/etc/mysql/conf.d/logzilla.cnf");
system("(cd $options->{lzroot}/scripts/contrib/Ubuntu_MySQL_Conf_Gen && ./Ubuntu12_my.cnf_gen.pl)");

if ($checkprocess) {
    print "Starting MySQL\n";
    system("service mysql start");
}

sub chk_ib_logs {
    my @f = </var/lib/mysql/ib_logfile*>;
    foreach my $f (@f) {
        next if $f =~ /orig/;
        my $size = -s $f;
        if ( $size <= 5242880 ) {
            print "Your ib_logfiles are too small (5MB)\n";
            print "Renaming $f to $f.orig. You can delete it later if you like.\n";
            system("mv $f $f.orig");
        }
    }
}

sub setup_mycnf {
    my $file = shift;
    my ($query_cache_size, $query_cache_limit);
    my $innodb_log_file_size;
    system("touch $file");
    my $numdisks = `fdisk -l 2>/dev/null | grep "Disk \/" | grep -v "\/dev\/md" | awk '{print \$2}' | sed -e 's/://g' | wc -l`;
    my $innodb_commit_concurrency = $numdisks * 4;
    # Below just grabs IOPS for the fastest disk, which we assume is where MySQL is running from...hopefully
    #my $diskio = `iostat | awk '{print \$2}' | sort -nr | head -1`;
    #chomp($diskio);
    #$diskio = sprintf("%.0f", $diskio);
    #$diskio = 200 if not ($diskio);
    my $cpu_cores = `cat /proc/cpuinfo | grep processor | wc -l`;
    my $cores2x   = $cpu_cores * 2;
    my $sysmem    = `cat /proc/meminfo |  grep "MemTotal" | awk '{print \$2}'`;
    $sysmem = ( $sysmem * 1024 );
    my $poolsize             = ( $sysmem * 3 / 10 );
    #my $innodb_log_file_size = ( $poolsize / 4 );

    if ( $sysmem >= 68719476736 ) {
        $innodb_log_file_size = 385875968;
    } elsif ( $sysmem >= 25769803776 ) {
        $innodb_log_file_size = 268435456;
    } elsif ( $sysmem >= 8589934592 ) {
        $innodb_log_file_size = 134217728;
    } else {
        $innodb_log_file_size = 67108864;
    }
    if ( $sysmem >= 68719476736 ) {
        $query_cache_size = 0;
        $query_cache_limit = 0;
    } else {
        $query_cache_size = "64M";
        $query_cache_limit = "512K";
    }

    my $innodb_log_buffer_size  = ( $innodb_log_file_size / 8 );
    my $Hpoolsize               = humanBytes($poolsize);
    my $Hinnodb_log_file_size   = humanBytes($innodb_log_file_size);
    my $Hinnodb_log_buffer_size = humanBytes($innodb_log_buffer_size);
    if ( -e "$file" ) {
        open my $config, '+<', "$file" or warn "FAILED: $!\n";
        my @arr = <$config>;
        if ( !grep( /logzilla|lzconfig/, @arr ) ) {
            print "Creating MySQL config for LogZilla at $file\n";
            open FILE, ">>$file" or die $!;
            print FILE <<EOF;
#<lzconfig> BEGIN LogZilla settings
# Based on http://www.mysqlperformanceblog.com/2007/11/01/innodb-performance-optimization-basics/
# And also from http://themattreid.com/uploads/innodb_flush_method-CNF-loadtest.txt
# Do not depend on these settings to be correct for your server. Please consult your DBA
# You can also run /var/www/logzilla/scripts/tools/mysqltuner.pl for help.
#
#
[mysqld]
#--------------------------------------
# General settings
#--------------------------------------
event_scheduler=on
symbolic-links=0
skip-name-resolve
#
#--------------------------------------
# Logging
#--------------------------------------
log-error=/var/log/mysql/error.log
#log=/var/log/mysql/general.log
#slow-query-log=/var/log/mysql/mysql-slow.log

# Log to the DB instead of files:
# http://www.dzone.com/snippets/log-sql-queries-mysql-table
# log-output = TABLE
# Disable logging in production environments.
# Uncomment below to enable for testing.
# slow-query-log 
# general-log
# long_query_time = 1
# expire_logs_days = 1

#--------------------------------------
# Files
#--------------------------------------
back_log                        = 300
open-files-limit                = 8192
open-files                      = 1024
port                            = 3306
skip-external-locking
skip-name-resolve

#--------------------------------------
## Per-Thread Buffers * (max_connections) = total per-thread mem usage
#--------------------------------------
thread_stack                    = 512K    #default: 32bit: 192K, 64bit: 256K
sort_buffer_size                = 2M      #default: 2M, larger may cause perf issues
read_buffer_size                = 2M      #default: 128K, change in increments of 4K
read_rnd_buffer_size            = 2M      #default: 256K
join_buffer_size                = 2M      #default: 128K
binlog_cache_size               = 128K    #default: 32K, size of buffer to hold TX queries

#--------------------------------------
## Query Cache
#--------------------------------------
# Disabling query cache relieves our hot path from unneeded processing and latency. 
# That cache would prove useful for regular MySQL workloads, so this should only be necessary on large systems.
query_cache_size                = $query_cache_size   #global buffer
query_cache_limit               = $query_cache_limit  #max query result size to put in cache

#--------------------------------------
## Connections
#--------------------------------------
max_connections                 = 1000  #multiplier for memory usage via per-thread buffers
thread_cache_size               = 50    #recommend 5% of max_connections
max_connect_errors              = 100   #default: 10
concurrent_insert               = 2     #default: 1, 2: enable insert for all instances
connect_timeout                 = 30    #default -5.1.22: 5, +5.1.22: 10
max_allowed_packet              = 32M   #max size of incoming data to allow

#--------------------------------------
## Table and TMP settings
## Use if you know what you are doing
#--------------------------------------
# max_heap_table_size             = 1G    #recommend same size as tmp_table_size
# bulk_insert_buffer_size         = 1G    #recommend same size as tmp_table_size
# tmp_table_size                  = 1G    #recommend 1G min
# tmpdir                         =  /dev/shm/db/tmp01:/dev/shm/db/tmp02:/dev/shm/db/tmp03 #Recommend using RAMDISK for tmpdir

#--------------------------------------
## Table cache settings
#--------------------------------------
#table_cache                    = 512   #5.0.x <default: 64>
table_open_cache                = 512   #5.1.x, 5.5.x <default: 64>

#--------------------------------------
## Thread settings
#--------------------------------------
# Disabled - deprecated and only works on Solaris 9
#thread_concurrency              = $cores2x  #recommend 2x CPU cores

#--------------------------------------
## MyISAM Engine
#--------------------------------------
key_buffer_size                 = 1M    #global buffer
myisam_sort_buffer_size         = 128M  #index buffer size for creating/altering indexes
myisam_max_sort_file_size       = 256M  #max file size for tmp table when creating/alering indexes
myisam_repair_threads           = 4     #thread quantity when running repairs
myisam_recover                  = BACKUP #repair mode, recommend BACKUP
myisam-block-size               = 14384
myisam_use_mmap
key_buffer_size                 = 128M  # This is the MyISAM equivalent of 'innodb_buffer_pool_size' for InnoDB.

#--------------------------------------
## InnoDB IO Capacity - 5.1.x plugin, 5.5.x
# http://dev.mysql.com/doc/refman/5.5/en/innodb-parameters.html#sysvar_innodb_io_capacity
#--------------------------------------
#innodb_io_capacity              = 20000 # Based on iostat for the fastest disk in your server

#--------------------------------------
## InnoDB IO settings -  5.1.x only
#--------------------------------------
#innodb_file_io_threads         = 16

#--------------------------------------
## InnoDB IO settings -  5.5.x and greater
#--------------------------------------
innodb_write_io_threads         = 64
innodb_read_io_threads          = 64

#--------------------------------------
## InnoDB Plugin Independent Settings
#--------------------------------------
# Can't set this unless you remove your current data
# innodb_data_file_path           = ibdata1:128M;ibdata2:10M:autoextend

# Note: If you modify innodb_log_file_size, you will first need to shut down mysql,
# and delete/rename your current /var/lib/mysql/ib_logfile* files so that mysql can create new ones.
# Check your /var/log/mysql/error.log on startup to make sure it worked properly.
innodb_log_file_size            = $Hinnodb_log_file_size #64G_RAM+ = 368, 24G_RAM+ = 256, 8G_RAM+ = 128, 2G_RAM+ = 64

innodb_log_files_in_group       = 3     #combined size of all logs <4GB. <16G_RAM = 2, >16G_RAM = 3
#
# Set innodb_buffer_pool_size to 10%-25% of total system memory if this is a dedicated LogZilla server
# This is negotiable, Percona recommends up to 80% but I've seen no improvements during testing
# (probably because we use external indexes)
# Also possibly helpful: http://stackoverflow.com/questions/5174396/innodb-performance-tweaks
innodb_buffer_pool_size         = $Hpoolsize
innodb_buffer_pool_instances    = 4     #ver 5.5+ only: splits buffer pool (req: buffer_pool/n > 1G) into n-chunks
innodb_additional_mem_pool_size = 4M    #global buffer
#innodb_status_file                      #extra reporting
innodb_file_per_table                   #enable always
innodb_flush_log_at_trx_commit  = 2     #2/0 = perf, 1 = ACID
innodb_table_locks              = 0     #preserve table locks
innodb_log_buffer_size          = $Hinnodb_log_buffer_size # Global buffer = 1/8 of the innodb_log_file_size
innodb_lock_wait_timeout        = 60
innodb_thread_concurrency       = $cores2x    #recommend 2x core quantity
innodb_commit_concurrency       = $innodb_commit_concurrency    #recommend 4x num disks
#innodb_flush_method             = O_DIRECT # use O_DIRECT if you have raid with bbu. Options: O_DIRECT, O_DSYNC, blank for fdatasync (default)
innodb_support_xa               = false #recommend 0 on read-only slave, disable xa to negate extra disk flush
skip-innodb-doublewrite
skip_innodb_checksums


#--------------------------------------
# Meta data stats
# Enable this to speed up log_processor startup.
# On slow, or very large servers, InnoDB can take > 30 seconds to start
# It's important that you know what you are doing this for, so please read before enabling it:
# http://dev.mysql.com/doc/refman/5.1/en/innodb-parameters.html#sysvar_innodb_stats_on_metadata
#--------------------------------------
# innodb_stats_on_metadata = 0


#</lzconfig> END LogZilla settings
EOF
        }
    }
    print "Installing new memory allocater for MySQL - see https://www.assembla.com/wiki/show/LogZillaWiki/MySQL_Tuning\n";
    system("apt-get -y install libjemalloc1");
    print "Adding memory allocator load to /etc/init/mysql.conf - see https://www.assembla.com/wiki/show/LogZillaWiki/MySQL_Tuning\n";
    system("perl -i -pe 's|env HOME=/etc/mysql|env HOME=/etc/mysql\nenv LD_PRELOAD=/usr/lib/libjemalloc.so.1\n|g' /etc/init/mysql.conf");
}

sub humanBytes {
    my $bytes = shift();
    if ( $bytes > 1099511627776 )    #   TB: 1024 GiB
    {
        return sprintf( "%.0fT", $bytes / 1099511627776 );
    }
    elsif ( $bytes > 1073741824 )    #   GB: 1024 MiB
    {
        return sprintf( "%.0fG", $bytes / 1073741824 );
    }
    elsif ( $bytes > 1048576 )       #   MB: 1024 KiB
    {
        return sprintf( "%.0fM", $bytes / 1048576 );
    }
    elsif ( $bytes > 1024 )          #   KB: 1024 B
    {
        return sprintf( "%.0fK", $bytes / 1024 );
    }
    else                             #   bytes
    {
        return "$bytes" . ( $bytes == 1 ? "" : "s" );
    }
}
sub prompt {
    my ( $prompt, $default ) = @_;
    my $defaultValue = $default ? "[$default]" : "";
    print "$prompt $defaultValue: ";
    chomp( my $input = <STDIN> );
    return $input ? $input : $default;
}

sub add_syslog_conf {
    my $now = localtime;
    my $dir = "/etc/syslog-ng/conf.d";
    my $file = "/etc/syslog-ng/conf.d/logzilla.conf";
    system("touch $file");
    unless ( -d "$dir" ) {
        $file = "/etc/syslog-ng/syslog-ng.conf";
        unless ( -e "$file" ) {
            $file = &prompt( "What is the correct path to your syslog-ng.conf file?", "/etc/syslog-ng/syslog-ng.conf" );
        }
    }
    if ( -e $file ) {
        open my $config, '+<', "$file";
        my @arr = <$config>;
        my $sconf = qq{
#<lzconfig> BEGIN LogZilla settings
# LogZilla "standard" config - this may or may not work well for your environment
# It is advisable that you learn what is best for your server.
# There's a great web gui available at http://mitzkia.github.com/syslog-ng-ose-configurator/#/howtouse
# Install Date: $now
};
my $sconf2 = q{
# Global Options
options {
chain_hostnames(no);
keep_hostname(yes);
threaded(yes); # enable if using Syslog-NG 3.3.x
#use_fqdn(no); # This should be set to no in high scale environments
#use_dns(yes); # This should be set to no in high scale environments
};

# Capture the program name for SNARE events
rewrite r_snare { 
subst("MSWinEventLog.+(Security|Application|System).+", "MSWin_$1", value("PROGRAM") flags(global)); 
};

# Snare sends TAB delimited messages, we need pipes...
rewrite r_snare2pipe { 
subst("\t", "|", value("MESSAGE") 
flags(global)
); 
};

# Grab Cisco Mnemonics and write program name
filter f_rw_cisco { match('^(%[A-Z]+\-\d\-[0-9A-Z]+): ([^\n]+)' value("MSGONLY") type("pcre") flags("store-matches" "nobackref")); };
filter f_rw_cisco_2 { match('^[\*\.]?(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{1,2}\s\d{1,2}:\d{1,2}:\d{1,2}(?:\.\d+)?(?: [A-Z]{3})?: (%[^:]+): ([^\n]+)' value("MSGONLY") type("pcre") flags("store-matches" "nobackref")); };
filter f_rw_cisco_3 { match('^\d+[ywdh]\d+[ywdh]: (%[^:]+): ([^\n]+)' value("MSGONLY") type("pcre") flags("store-matches" "nobackref")); };
filter f_rw_cisco_4 { match('^\d{6}: [\*\.]?(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{1,2}\s\d{1,2}:\d{1,2}:\d{1,2}(?:\.\d+)?(?: [A-Z]{3})?: (%[^:]+): ([^\n]+)' value("MSGONLY") type("pcre") flags("store-matches" "nobackref")); };

rewrite r_cisco_program {
set("Cisco_Syslog", value("PROGRAM") condition(filter(f_rw_cisco) or filter(f_rw_cisco_2) or filter(f_rw_cisco_3) or filter(f_rw_cisco_4)));
set("$1: $2", value("MESSAGE") condition(filter(f_rw_cisco) or filter(f_rw_cisco_2) or filter(f_rw_cisco_3) or filter(f_rw_cisco_4)));
};

source s_logzilla {
# Use no-multi-line so that java events get read properly
tcp(flags(no-multi-line));
udp(flags(no-multi-line));
};

destination d_logzilla {
program(
"/var/www/logzilla/scripts/logzilla"
log_fifo_size(1000)
flush_lines(100)
flush_timeout(1)
template("$R_YEAR-$R_MONTH-$R_DAY $R_HOUR:$R_MIN:$R_SEC\t$HOST\t$PRI\t$PROGRAM\t$MSGONLY\n")
);
};

destination df_logzilla {
file("/var/log/logzilla/DEBUG.log"
template("$R_YEAR-$R_MONTH-$R_DAY $R_HOUR:$R_MIN:$R_SEC\t$HOST\t$PRI\t$PROGRAM\t$MSGONLY\n")
); 
};

log {
source(s_logzilla);
rewrite(r_snare);
rewrite(r_snare2pipe);
rewrite(r_cisco_program);
destination(d_logzilla);
# Uncomment below and restart syslog-ng for debugging
# destination(df_logzilla);
flags(flow-control);
};
#</lzconfig> END LogZilla settings
};
if ( !grep( /logzilla|lzconfig/, @arr ) ) {
    print "Creating LogZilla configuration for syslog-ng at $file\n";
    open FILE, ">>$file" or die $!;
    print FILE $sconf . $sconf2;
} else {
    print "Skipping syslog-ng config as $file already exists...\n";
}
}
}

print "All Done\n";
