/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of Fast.xs. Do not edit this file, edit Fast.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Fast.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "LogSyslogFast.h"

#include "const-c.inc"

#line 21 "Fast.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 73 "Fast.c"

/* INCLUDE:  Including 'const-xs.inc' from 'Fast.xs' */


XS(XS_Log__Syslog__Fast_constant); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_constant)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "./const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	/* IV		iv;	Uncomment this if you need to return IVs */
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 102 "Fast.c"
	SV *	sv = ST(0);
	const char *	s = SvPV(sv, len);
#line 18 "./const-xs.inc"
	type = constant(aTHX_ s, len);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid Log::Syslog::Fast macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined Log::Syslog::Fast macro %s, used",
				   s));
          PUSHs(sv);
          break;
	/* Uncomment this if you need to return IVs
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break; */
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing Log::Syslog::Fast macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 178 "Fast.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'Fast.xs' from 'const-xs.inc' */


XS(XS_Log__Syslog__Fast_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 8)
       croak_xs_usage(cv,  "class, proto, hostname, port, facility, severity, sender, name");
    {
	char*	class;
	int	proto = (int)SvIV(ST(1));
	char*	hostname;
	int	port = (int)SvIV(ST(3));
	int	facility = (int)SvIV(ST(4));
	int	severity = (int)SvIV(ST(5));
	char*	sender;
	char*	name;
	LogSyslogFast *	RETVAL;

                    if (ST(0) == &PL_sv_undef)
                        class = NULL;
                    else
                        class = (char *)SvPV_nolen(ST(0));

                    if (ST(2) == &PL_sv_undef)
                        hostname = NULL;
                    else
                        hostname = (char *)SvPV_nolen(ST(2));

                    if (ST(6) == &PL_sv_undef)
                        sender = NULL;
                    else
                        sender = (char *)SvPV_nolen(ST(6));

                    if (ST(7) == &PL_sv_undef)
                        name = NULL;
                    else
                        name = (char *)SvPV_nolen(ST(7));
#line 28 "Fast.xs"
    if (!hostname)
        croak("hostname required");
    if (!sender)
        croak("sender required");
    if (!name)
        croak("name required");
    RETVAL = LSF_alloc();
    if (!RETVAL)
        croak("Error in ->new: malloc failed");
    if (LSF_init(RETVAL, proto, hostname, port, facility, severity, sender, name) < 0)
        croak("Error in ->new: %s", RETVAL->err);
#line 240 "Fast.c"
	ST(0) = sv_newmortal();
                    sv_setref_pv( ST(0), "Log::Syslog::Fast", (void*)RETVAL );
    }
    XSRETURN(1);
}


XS(XS_Log__Syslog__Fast_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "logger");
    {
	LogSyslogFast*	logger;

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::DESTROY() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };
#line 46 "Fast.xs"
    if (LSF_destroy(logger))
        croak("Error in close: %s", logger->err);
#line 270 "Fast.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Log__Syslog__Fast_send); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_send)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    dXSI32;
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "logger, logmsg, now = time(0)");
    {
	LogSyslogFast*	logger;
	SV*	logmsg = ST(1);
	time_t	now;
	int	RETVAL;
	dXSTARG;

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::send() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };

	if (items < 3)
	    now = time(0);
	else {
	    now = (time_t)SvNV(ST(2));
	}
#line 57 "Fast.xs"
    STRLEN msglen;
    const char* msgstr;
    msgstr = SvPV(logmsg, msglen);
#line 310 "Fast.c"
#line 61 "Fast.xs"
    RETVAL = LSF_send(logger, msgstr, msglen, now);
    if (RETVAL < 0)
        croak("Error while sending: %s", logger->err);
#line 315 "Fast.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Log__Syslog__Fast_set_receiver); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_set_receiver)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    dXSI32;
    if (items != 4)
       croak_xs_usage(cv,  "logger, proto, hostname, port");
    {
	LogSyslogFast*	logger;
	int	proto = (int)SvIV(ST(1));
	char*	hostname;
	int	port = (int)SvIV(ST(3));

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::set_receiver() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };

                    if (ST(2) == &PL_sv_undef)
                        hostname = NULL;
                    else
                        hostname = (char *)SvPV_nolen(ST(2));
#line 76 "Fast.xs"
    if (!hostname)
        croak("hostname required");
    int ret = LSF_set_receiver(logger, proto, hostname, port);
    if (ret < 0)
        croak("Error in set_receiver: %s", logger->err);
#line 356 "Fast.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Log__Syslog__Fast_set_priority); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_set_priority)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    dXSI32;
    if (items != 3)
       croak_xs_usage(cv,  "logger, facility, severity");
    {
	LogSyslogFast*	logger;
	int	facility = (int)SvIV(ST(1));
	int	severity = (int)SvIV(ST(2));

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::set_priority() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };
#line 90 "Fast.xs"
    LSF_set_priority(logger, facility, severity);
#line 386 "Fast.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Log__Syslog__Fast_set_facility); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_set_facility)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "logger, facility");
    {
	LogSyslogFast*	logger;
	int	facility = (int)SvIV(ST(1));

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::set_facility() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };
#line 97 "Fast.xs"
    LSF_set_facility(logger, facility);
#line 414 "Fast.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Log__Syslog__Fast_set_severity); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_set_severity)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "logger, severity");
    {
	LogSyslogFast*	logger;
	int	severity = (int)SvIV(ST(1));

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::set_severity() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };
#line 104 "Fast.xs"
    LSF_set_severity(logger, severity);
#line 442 "Fast.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Log__Syslog__Fast_set_sender); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_set_sender)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    dXSI32;
    if (items != 2)
       croak_xs_usage(cv,  "logger, sender");
    {
	LogSyslogFast*	logger;
	char*	sender;

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::set_sender() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };

                    if (ST(1) == &PL_sv_undef)
                        sender = NULL;
                    else
                        sender = (char *)SvPV_nolen(ST(1));
#line 113 "Fast.xs"
    if (!sender)
        croak("sender required");
    int ret = LSF_set_sender(logger, sender);
    if (ret < 0)
        croak("Error in set_sender: %s", logger->err);
#line 480 "Fast.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Log__Syslog__Fast_set_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_set_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    dXSI32;
    if (items != 2)
       croak_xs_usage(cv,  "logger, name");
    {
	LogSyslogFast*	logger;
	char*	name;

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::set_name() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };

                    if (ST(1) == &PL_sv_undef)
                        name = NULL;
                    else
                        name = (char *)SvPV_nolen(ST(1));
#line 126 "Fast.xs"
    if (!name)
        croak("name required");
    int ret = LSF_set_name(logger, name);
    if (ret < 0)
        croak("Error in set_name: %s", logger->err);
#line 518 "Fast.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Log__Syslog__Fast_set_pid); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_set_pid)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    dXSI32;
    if (items != 2)
       croak_xs_usage(cv,  "logger, pid");
    {
	LogSyslogFast*	logger;
	int	pid = (int)SvIV(ST(1));

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::set_pid() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };
#line 139 "Fast.xs"
    LSF_set_pid(logger, pid);
#line 547 "Fast.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Log__Syslog__Fast_set_format); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_set_format)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    dXSI32;
    if (items != 2)
       croak_xs_usage(cv,  "logger, format");
    {
	LogSyslogFast*	logger;
	int	format = (int)SvIV(ST(1));

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::set_format() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };
#line 148 "Fast.xs"
    int ret = LSF_set_format(logger, format);
    if (ret < 0)
        croak("Error in set_format: %s", logger->err);
#line 578 "Fast.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Log__Syslog__Fast_get_priority); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_get_priority)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "logger");
    {
	LogSyslogFast*	logger;
	int	RETVAL;
	dXSTARG;

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::get_priority() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };
#line 156 "Fast.xs"
    RETVAL = LSF_get_priority(logger);
#line 607 "Fast.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Log__Syslog__Fast_get_facility); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_get_facility)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "logger");
    {
	LogSyslogFast*	logger;
	int	RETVAL;
	dXSTARG;

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::get_facility() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };
#line 164 "Fast.xs"
    RETVAL = LSF_get_facility(logger);
#line 637 "Fast.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Log__Syslog__Fast_get_severity); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_get_severity)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "logger");
    {
	LogSyslogFast*	logger;
	int	RETVAL;
	dXSTARG;

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::get_severity() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };
#line 172 "Fast.xs"
    RETVAL = LSF_get_severity(logger);
#line 667 "Fast.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Log__Syslog__Fast_get_sender); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_get_sender)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "logger");
    {
	LogSyslogFast*	logger;
	const char *	RETVAL;
	dXSTARG;

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::get_sender() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };
#line 180 "Fast.xs"
    RETVAL = LSF_get_sender(logger);
#line 697 "Fast.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Log__Syslog__Fast_get_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_get_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "logger");
    {
	LogSyslogFast*	logger;
	const char *	RETVAL;
	dXSTARG;

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::get_name() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };
#line 188 "Fast.xs"
    RETVAL = LSF_get_name(logger);
#line 727 "Fast.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Log__Syslog__Fast_get_pid); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_get_pid)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "logger");
    {
	LogSyslogFast*	logger;
	int	RETVAL;
	dXSTARG;

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::get_pid() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };
#line 196 "Fast.xs"
    RETVAL = LSF_get_pid(logger);
#line 757 "Fast.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Log__Syslog__Fast_get_format); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast_get_format)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "logger");
    {
	LogSyslogFast*	logger;
	int	RETVAL;
	dXSTARG;

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::get_format() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };
#line 204 "Fast.xs"
    RETVAL = LSF_get_format(logger);
#line 787 "Fast.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Log__Syslog__Fast__get_sock); /* prototype to pass -Wmissing-prototypes */
XS(XS_Log__Syslog__Fast__get_sock)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "logger");
    {
	LogSyslogFast*	logger;
	int	RETVAL;
	dXSTARG;

                    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
                        logger = (LogSyslogFast *)SvIV((SV*)SvRV(ST(0)));
                    else {
                        warn("Log::Syslog::Fast::_get_sock() -- logger is not a blessed SV reference");
                        XSRETURN_UNDEF;
                    };
#line 212 "Fast.xs"
    RETVAL = LSF_get_sock(logger);
#line 817 "Fast.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Log__Syslog__Fast); /* prototype to pass -Wmissing-prototypes */
XS(boot_Log__Syslog__Fast)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

    {
        CV * cv ;

        newXS("Log::Syslog::Fast::constant", XS_Log__Syslog__Fast_constant, file);
        (void)newXSproto_portable("Log::Syslog::Fast::new", XS_Log__Syslog__Fast_new, file, "$$$$$$$$");
        (void)newXSproto_portable("Log::Syslog::Fast::DESTROY", XS_Log__Syslog__Fast_DESTROY, file, "$");
        cv = newXSproto_portable("Log::Syslog::Fast::send", XS_Log__Syslog__Fast_send, file, "$$;$");
        XSANY.any_i32 = 0 ;
        cv = newXSproto_portable("Log::Syslog::Fast::emit", XS_Log__Syslog__Fast_send, file, "$$;$");
        XSANY.any_i32 = 1 ;
        cv = newXSproto_portable("Log::Syslog::Fast::set_receiver", XS_Log__Syslog__Fast_set_receiver, file, "$$$$");
        XSANY.any_i32 = 0 ;
        cv = newXSproto_portable("Log::Syslog::Fast::setReceiver", XS_Log__Syslog__Fast_set_receiver, file, "$$$$");
        XSANY.any_i32 = 1 ;
        cv = newXSproto_portable("Log::Syslog::Fast::set_priority", XS_Log__Syslog__Fast_set_priority, file, "$$$");
        XSANY.any_i32 = 0 ;
        cv = newXSproto_portable("Log::Syslog::Fast::setPriority", XS_Log__Syslog__Fast_set_priority, file, "$$$");
        XSANY.any_i32 = 1 ;
        (void)newXSproto_portable("Log::Syslog::Fast::set_facility", XS_Log__Syslog__Fast_set_facility, file, "$$");
        (void)newXSproto_portable("Log::Syslog::Fast::set_severity", XS_Log__Syslog__Fast_set_severity, file, "$$");
        cv = newXSproto_portable("Log::Syslog::Fast::setSender", XS_Log__Syslog__Fast_set_sender, file, "$$");
        XSANY.any_i32 = 1 ;
        cv = newXSproto_portable("Log::Syslog::Fast::set_sender", XS_Log__Syslog__Fast_set_sender, file, "$$");
        XSANY.any_i32 = 0 ;
        cv = newXSproto_portable("Log::Syslog::Fast::set_name", XS_Log__Syslog__Fast_set_name, file, "$$");
        XSANY.any_i32 = 0 ;
        cv = newXSproto_portable("Log::Syslog::Fast::setName", XS_Log__Syslog__Fast_set_name, file, "$$");
        XSANY.any_i32 = 1 ;
        cv = newXSproto_portable("Log::Syslog::Fast::set_pid", XS_Log__Syslog__Fast_set_pid, file, "$$");
        XSANY.any_i32 = 0 ;
        cv = newXSproto_portable("Log::Syslog::Fast::setPid", XS_Log__Syslog__Fast_set_pid, file, "$$");
        XSANY.any_i32 = 1 ;
        cv = newXSproto_portable("Log::Syslog::Fast::setFormat", XS_Log__Syslog__Fast_set_format, file, "$$");
        XSANY.any_i32 = 1 ;
        cv = newXSproto_portable("Log::Syslog::Fast::set_format", XS_Log__Syslog__Fast_set_format, file, "$$");
        XSANY.any_i32 = 0 ;
        (void)newXSproto_portable("Log::Syslog::Fast::get_priority", XS_Log__Syslog__Fast_get_priority, file, "$");
        (void)newXSproto_portable("Log::Syslog::Fast::get_facility", XS_Log__Syslog__Fast_get_facility, file, "$");
        (void)newXSproto_portable("Log::Syslog::Fast::get_severity", XS_Log__Syslog__Fast_get_severity, file, "$");
        (void)newXSproto_portable("Log::Syslog::Fast::get_sender", XS_Log__Syslog__Fast_get_sender, file, "$");
        (void)newXSproto_portable("Log::Syslog::Fast::get_name", XS_Log__Syslog__Fast_get_name, file, "$");
        (void)newXSproto_portable("Log::Syslog::Fast::get_pid", XS_Log__Syslog__Fast_get_pid, file, "$");
        (void)newXSproto_portable("Log::Syslog::Fast::get_format", XS_Log__Syslog__Fast_get_format, file, "$");
        (void)newXSproto_portable("Log::Syslog::Fast::_get_sock", XS_Log__Syslog__Fast__get_sock, file, "$");
    }
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

