---
abstract: 'Perl extension for sending syslog messages over TCP, UDP,'
author:
  - 'Adam Thomason <athomason@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Syslog-Fast
no_index:
  directory:
    - t
    - inc
requires:
  Log::Syslog::Constants: 1.01
version: 0.61
