#!/bin/bash
hn=`hostname`
apache_log="/var/log/apache2/error.log"
lz="/var/www/logzilla"

if [[ $EUID -ne 0 ]]; then
       echo "This script must be run as root - if you are using Ubuntu, try \"sudo $0\"" 1>&2
          exit 1
      fi

#######################################
# Prompt for a value
#######################################
f_ANSWER()
{
        printf "%s " "$1"
        if [ "$2" != "" ] ; then
                printf "[%s] " "$2"
        fi 
        if [ "${DEFAULT:-0}" -eq 0 ] ; then
                read ANSWER
        else
                printf "%s\n" "$2"
        fi
        if [ "$ANSWER" = "" ] ; then
                ANSWER="$2"
        fi
}

echo "Collecting Support Information..."
ifconfig -a > $hn.ifconfig.log
$lz/scripts/tools/summary > $hn.summary.log

if [ -e "$apache_log" ]; then
    tail -20 /var/log/apache2/error.log > $hn.apache_error.log
else
    echo "Unable to locate your apache error log"
    f_ANSWER "Where is your Apache Error log located?" "$apache_log"
    apachelog=$ANSWER
fi

printf "`date \"+%Y-%m-%d %H:%M:%S\"`\ttest\t190\tCRON\tTest From LogZilla Support\n" | $lz/scripts/db_insert.pl -d5 -v > $hn.dbtest.log  2>&1 

cat /var/www/logzilla/scripts/install.pl | grep -E "version\s+=" > $hn.lzver.log 2>&1

tar czvf $hn.tgz $hn.*.log
rm -f $hn.apache_error.log
rm -f $hn.dbtest.log
rm -f $hn.ifconfig.log
rm -f $hn.summary.log
rm -f $hn.lzver.log
echo
echo "Completed."
echo "Please email $hn.tgz to support@logzilla.pro, or visit http://support.logzilla.pro an attach to your ticket online"

