#!/bin/bash
lzhome="/path_to_logzilla"
[ ! -d "$lzhome" ] && lzhome="/var/www/logzilla"

# Set ulimit for max processes and open files
ulimit -u 4096 -n 65536

# -------------------------------------------
# Check to see if we are already running.
# -------------------------------------------
PID=`ps aux | grep "idx-rotate" | grep -v grep | awk '{print $2}'`
if [ "$PID" ]; then
    echo "LogZilla daily index rotation is already running on PID $PID" >&2
    exit 1
fi

# Restart searchd in case all indexes are not up to date
[[ -f /etc/init.d/logzilla ]] && service logzilla stop || (cd $lzhome/sphinx && ./bin/searchd --stopwait)
[[ -f /etc/init.d/logzilla ]] && service logzilla start || (cd $lzhome/sphinx && ./run_searchd.sh)

/var/www/logzilla/scripts/idx-rotate -v -r idx_rotate 

