#!/bin/bash
lzhome="/path_to_logzilla"
[ ! -d "$lzhome" ] && lzhome="/var/www/logzilla"

ulimit -Hn 4096
ulimit -Sn 4096

# -------------------------------------------
# Check to see if we are already running.
# -------------------------------------------
PID=`ps aux | grep "idx-rotate" | grep -v grep | awk '{print $2}'`
if [ "$PID" ]; then
    echo "LogZilla daily index rotation is already running on PID $PID" >&2
    exit 1
fi

/var/www/logzilla/scripts/idx-rotate -v -r idx_rotate 
